### ISSUE TITLE
Installation of inotify-tools

### ISSUE THREAD

**Issue by ttokutake** [kasaharu/himatsubushi#1]
- 基本的な流れ: http://blog.shinelll.xyz/2015/11/23/centos-7_inotify-tools/
- ダウンロードURL: https://github.com/rvoicilas/inotify-tools/wiki#getting-inotify-tools
- curl時の注意: http://stackoverflow.com/questions/5746325/how-do-i-download-a-tarball-from-github-using-curl

あとはrootでコンパイル&インストールでOK

**Comment by kasaharu** [comment]
refer #2
